### ISSUE TITLE
Automatically open project after creation

### ISSUE THREAD

**Issue by Ball-Man** [bit101/ProjectMaker#55] opened 2018-03-20 22:21 UTC
This isn't currently happening. Actually, I don't know if this should or should not happen, but it's indeed very useful(if not always, at least an option that lets you decide wheter or not do it).
I took a look at the source and found out that I probably could add this feature myself(eventually a PR) but since I'm not very familiar with sublime plugins I'm firstly reporting here this thought.

**Comment by pykong** [comment] 2018-03-21 12:28
@Ball-Man Have many thanks for your interest in this plugin and also for offering a PR.
Indeed this would be a highly desirable feature.

Hence it is implemented via #53 
Also duplicate of #44

**Closed by pykong** 2018-03-21 12:28 UTC
